[workspace]
members = ["xtask"]
default-members = ["."]
resolver = "3"

[package]
name = "xdg-desktop-portal-logind"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
async-lock = "3"
futures-lite = "2"
zbus = "5.19"

[dev-dependencies]
async-channel = "2"
async-io = "2"
tempfile = "3"
